### ISSUE TITLE
ReadDiversionHistoricalTSMonthlyFromHydroBase FillUsingCIU=True command parameter not working

### ISSUE THREAD

**Issue by macphersonbr** [OpenCDSS/cdss-app-statedmi-main#103]
When trying to run a command such as: ReadDiversionHistoricalTSMonthlyFromHydroBase(ID="*",IncludeCollections=False,UseDiversionComments=True,FillUsingCIU="True")

I am receiving the following:

Problem: Unexpected error reading diversion historical time series (java.lang.NullPointerException).

I am using StateDMI 5.00.03dev and HydroBase_CO_20210322. .log file attached:
[StateDMI_bdm.log](https://github.com/OpenCDSS/cdss-app-statedmi-main/files/6818690/StateDMI_bdm.log)

The issue only appears after adding the command parameter FillUsingCIU="True". 

Command file and required files attached (remove .txt extension):

[ddhCU.commands_CIU.StateDMI.txt](https://github.com/OpenCDSS/cdss-app-statedmi-main/files/6849321/ddhCU.commands_CIU.StateDMI.txt)
[strlist_cu.csv.txt](https://github.com/OpenCDSS/cdss-app-statedmi-main/files/6849323/strlist_cu.csv.txt)
[sj_agg.csv.txt](https://github.com/OpenCDSS/cdss-app-statedmi-main/files/6849325/sj_agg.csv.txt)
[sj_divsys_divCU.csv.txt](https://github.com/OpenCDSS/cdss-app-statedmi-main/files/6849326/sj_divsys_divCU.csv.txt)
[fill2015.pat.txt](https://github.com/OpenCDSS/cdss-app-statedmi-main/files/6849973/fill2015.pat.txt)
[Dolores_Project.stm.txt](https://github.com/OpenCDSS/cdss-app-statedmi-main/files/6849978/Dolores_Project.stm.txt)
[Historic_Florida.stm.txt](https://github.com/OpenCDSS/cdss-app-statedmi-main/files/6849983/Historic_Florida.stm.txt)
[Task11.2.stm.txt](https://github.com/OpenCDSS/cdss-app-statedmi-main/files/6849985/Task11.2.stm.txt)
[SanMiguel.stm.txt](https://github.com/OpenCDSS/cdss-app-statedmi-main/files/6849990/SanMiguel.stm.txt)

**Comment by smalers** [comment]
I need Brian to upload the `fill2015.pat` file.

**Comment by macphersonbr** [comment]
Uploaded fill2015.pat and other .stm files.

**Comment by smalers** [comment]
The problem occurred because `FillUsingCIU=True` but `FillUsingCIUFlag` was not set.  In previous work, the two must have both been set and the error was not detected.  The code did not default to empty string for `FillUsingCIUFlag`, as intended.  I fixed the code.  I will issue a release ASAP so that the software can be confirmed.  However, I do suggest that the `FillUsingCIUFlag` is specified.  There are probably historical reasons for the way it is.

I am going to add a separate issue to consider changing the default flag to `Auto` and allow longer than 1 character flag, but I don't have a reason to change that right now.  These are minutia related to modeling.

**Comment by smalers** [comment]
I ran with all the input files provided by Brian.  It looks like the `Dolores_Project.stm` file does not include `3200772`.

Some other time series also have issues being filled.  It looks like there is no data for those time series.

I assume that Brian or someone else is in the process of doing some updates so maybe there are other issues like identifiers changing in the original data sources.

**I'm going to let Brian decide whether to close this issue.**

**Comment by macphersonbr** [comment]
Adding closing comment: Comment was closed because adding a parameter FillUsingCIUFlag=Auto fixed the issue in the command file.
